[package]
name = "authorized_users"
version = "0.11.8"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
log = "0.4"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
uuid = { version = "1.0", features = ["serde", "v4"] }
tokio = {version="1.34", features=["rt", "macros", "rt-multi-thread"]}
derive_more = "0.99"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
bytes = "1.1"
base64 = "0.21"
rand = "0.8"
smallvec = "1.8"
crossbeam = "0.8"
arc-swap = "1.5"
biscuit = "0.7"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", features=["postgres_types"], tag="0.9.2" }
reqwest = {version="0.11", features=["cookies", "json", "rustls-tls", "stream"], default_features=false}
url = "2.3"