[package]
name = "authorized_users"
version = "0.8.8"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
log = "0.4"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
uuid = { version = "1.0", features = ["serde", "v4"] }
tokio = {version="1.19", features=["full"]}
derive_more = "0.99"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
bytes = "1.1"
base64 = "0.13"
rand = "0.8"
smallvec = "1.8"
crossbeam = "0.8"
arc-swap = "1.5"
im = "15.0"
biscuit = "0.5"
stack-string = { version="0.7", features=["postgres_types"] }
reqwest = {version="0.11", features=["cookies", "json", "rustls-tls", "stream"], default_features=false}
url = "2.2"