[package]
name = "authorized_users"
version = "0.11.9"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.5"
base64 = "0.21"
biscuit = "0.7"
bytes = "1.1"
crossbeam = "0.8"
derive_more = "0.99"
log = "0.4"
once_cell = "1.0"
rand = "0.8"
reqwest = {version="0.11", features=["cookies", "json", "rustls-tls", "stream"], default_features=false}
serde = { version="1.0", features=["derive"] }
smallvec = "1.8"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", features=["postgres_types"], tag="0.9.2" }
thiserror = "1.0"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
tokio = {version="1.34", features=["rt", "macros", "rt-multi-thread"]}
url = "2.3"
uuid = { version = "1.0", features = ["serde", "v4"] }
