[package]
name = "auth_server_rust"
version = "0.1.1"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0"
actix = "0.10"
actix-identity = "0.3"
anyhow = "1.0"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
tokio = {version="0.2", features=["full"]}
thiserror = "1.0"
dirs = "3.0"
dotenv = "0.15"
derive_more = "0.99"
rusoto_core = {version = "0.45", default_features = false, features=["rustls"]}
rusoto_ses = {version = "0.45", default_features = false, features=["rustls"]}
sts_profile_auth = "0.5"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
serde_json="1.0"
deadpool = "0.5"
deadpool-postgres = "0.5"
tokio-postgres = {version = "0.5", features = ["with-chrono-0_4", "with-uuid-0_8"]}
postgres-types = "0.1"
postgres_query = "0.3"
jsonwebtoken = "7.2"
bcrypt = "0.8"
bytes = "0.5"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.6", features=["postgres_types"] }
envy = "0.4"
base64 = "0.12"
openid = "0.4"
rand = "0.7"
url = "2.1"
futures = "0.3"
parking_lot = "0.11"

[[bin]]
name = "auth-server-rust"
path = "src/main.rs"
doc = false
