FROM rust_stable:latest
MAINTAINER Daniel Boline

WORKDIR /auth_server_rust

ADD Cargo.toml /auth_server_rust
ADD src /auth_server_rust/src
ADD auth_server_ext /auth_server_rust/auth_server_ext
ADD auth_server_lib /auth_server_rust/auth_server_lib
ADD auth_server_http /auth_server_rust/auth_server_http
ADD authorized_users /auth_server_rust/authorized_users
ADD scripts /auth_server_rust/scripts
ADD Makefile /auth_server_rust
ADD templates /auth_server_rust/templates
