ALTER TABLE sessions ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE invitations ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE session_values ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;