[package]
name = "auth_server_lib"
version = "0.3.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
authorized_users = {path = "../authorized_users"}
actix-web = "4.0.0-beta.1"
actix-rt = "2.0.0-beta.1"
anyhow = "1.0"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
tokio = {version="1.0", features=["full"]}
thiserror = "1.0"
dirs = "3.0"
dotenv = "0.15"
derive_more = "0.99"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
serde_json="1.0"
deadpool = "0.7"
deadpool-postgres = "0.7"
tokio-postgres = {version = "0.7", features = ["with-chrono-0_4", "with-uuid-0_8"]}
postgres-types = "0.2"
postgres_query = {git = "https://github.com/ddboline/rust-postgres-query", branch="master"}
bcrypt = "0.9"
bytes = "1.0"
envy = "0.4"
base64 = "0.13"
rand = "0.8"
url = "2.2"
futures = "0.3"
parking_lot = "0.11"
smallvec = "1.6"
crossbeam = "0.8"
arc-swap = "1.2"
im = "15.0"
toml = "0.5"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.2.0", features=["postgres_types"] }
