[package]
name = "auth_server_ext"
version = "0.10.4"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_server_lib = {path = "../auth_server_lib"}
authorized_users = {path = "../authorized_users"}
anyhow = "1.0"
log = "0.4"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting", "parsing"]}
uuid = { version = "1.0", features = ["serde", "v4"] }
tokio = {version="1.21", features=["full"]}
thiserror = "1.0"
dirs = "4.0"
dotenv = "0.15"
derive_more = "0.99"
rusoto_core = {version = "0.48", default_features = false, features=["rustls"]}
rusoto_ses = {version = "0.48", default_features = false, features=["rustls"]}
sts_profile_auth = "0.7"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
serde_json="1.0"
bytes = "1.1"
envy = "0.4"
base64 = "0.21"
openid = {version="0.11", default-features=false}
rand = "0.8"
url = "2.3"
futures = "0.3"
parking_lot = "0.12"
smallvec = "1.8"
crossbeam = "0.8"
arc-swap = "1.5"
toml = "0.7"
stack-string = { version="0.8", features=["postgres_types"] }

[dev-dependencies]
reqwest = {version = "0.11", default_features = false, features=["cookies", "rustls-tls", "gzip", "json"]}
