[package]
name = "auth_server_ext"
version = "0.11.3"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_server_lib = {path = "../auth_server_lib"}
authorized_users = {path = "../authorized_users"}
aws-config = {version="1.0", features=["behavior-version-latest"]}
aws-sdk-ses = "1.1"
aws-smithy-types = "1.0"
log = "0.4"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting", "parsing"]}
uuid = { version = "1.0", features = ["serde", "v4"] }
tokio = {version="1.34", features=["full"]}
thiserror = "1.0"
dirs = "5.0"
dotenv = "0.15"
derive_more = "0.99"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
serde_json="1.0"
bytes = "1.1"
envy = "0.4"
base64 = "0.21"
openid = {version="0.12", default-features=false}
rand = "0.8"
url = "2.3"
futures = "0.3"
parking_lot = "0.12"
smallvec = "1.8"
crossbeam = "0.8"
arc-swap = "1.5"
toml = "0.8"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", features=["postgres_types"], tag="0.9.2" }
refinery = {version="0.8", features=["tokio-postgres"]}

[dev-dependencies]
reqwest = {version = "0.11", default_features = false, features=["cookies", "rustls-tls", "gzip", "json"]}
