[package]
name = "auth_server_http"
version = "0.11.6"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_server_ext = {path = "../auth_server_ext"}
auth_server_lib = {path="../auth_server_lib"}
authorized_users = {path = "../authorized_users"}
arc-swap = "1.5"
aws-config = {version="1.0", features=["behavior-version-latest"]}
cookie = {version="0.18", features=["percent-encode"]}
derive_more = "0.99"
dioxus-ssr = "0.4"
dioxus = "0.4"
futures = "0.3"
log = "0.4"
maplit = "1.0"
parking_lot = "0.12"
rand = "0.8"
serde = { version="1.0", features=["derive"] }
serde_json="1.0"
serde_yaml = "0.9"
thiserror = "1.0"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting", "parsing"]}
tokio = {version="1.34", features=["rt", "macros", "rt-multi-thread"]}
toml = "0.8"
url = "2.3"
uuid = { version = "1.0", features = ["serde", "v4"] }
warp = "0.3"
rweb = {git = "https://github.com/ddboline/rweb.git", features=["openapi"], default-features=false, tag="0.15.1-1"}
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", features=["postgres_types", "rweb-openapi"], tag="0.9.2" }
rweb-helper = {git = "https://github.com/ddboline/rweb_helper.git", tag="0.5.0-1"}

[dev-dependencies]
anyhow = "1.0"
reqwest = {version = "0.11", default_features = false, features=["cookies", "rustls-tls", "gzip", "json"]}
maplit = "1.0"
env_logger = "0.10"
