[package]
name = "auth_server_http"
version = "0.10.12"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auth_server_ext = {path = "../auth_server_ext"}
auth_server_lib = {path="../auth_server_lib"}
authorized_users = {path = "../authorized_users"}
warp = "0.3"
http = "0.2"
biscuit = "0.6"
log = "0.4"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting", "parsing"]}
uuid = { version = "1.0", features = ["serde", "v4"] }
tokio = {version="1.26", features=["full"]}
thiserror = "1.0"
dirs = "5.0"
dotenv = "0.15"
derive_more = "0.99"
rusoto_core = {version = "0.48", default_features = false, features=["rustls"]}
rusoto_ses = {version = "0.48", default_features = false, features=["rustls"]}
sts_profile_auth = "0.7"
lazy_static = "1.4"
serde = { version="1.0", features=["derive"] }
serde_json="1.0"
bytes = "1.1"
envy = "0.4"
rand = "0.8"
url = "2.3"
futures = "0.3"
parking_lot = "0.12"
smallvec = "1.8"
crossbeam = "0.8"
arc-swap = "1.5"
toml = "0.7"
rweb = {git = "https://github.com/ddboline/rweb.git", features=["openapi"], default-features=false, tag="0.15.1-1"}
serde_yaml = "0.9"
indexmap = "1.9"
maplit = "1.0"
cookie = {version="0.17", features=["percent-encode"]}
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", features=["postgres_types", "rweb-openapi"], tag="0.9.2" }
rweb-helper = {git = "https://github.com/ddboline/rweb_helper.git", tag="0.5.0-1"}
postgres_query = {git = "https://github.com/ddboline/rust-postgres-query", tag = "0.3.4", features=["deadpool"]}
dioxus-ssr = "0.4"
dioxus = "0.4"

[dev-dependencies]
reqwest = {version = "0.11", default_features = false, features=["cookies", "rustls-tls", "gzip", "json"]}
maplit = "1.0"
env_logger = "0.10"
