openapi: '3.1.0'
info:
  title: Rust Autorization Server
  description: Authorization Server written in rust using jwt/jws/jwe and featuring integration with Google OAuth
  contact:
    name: Daniel Boline
    email: ddboline@gmail.com
  license:
    name: MIT
    identifier: MIT
  version: '0.13.1'
paths:
  /api/auth:
    get:
      operationId: test_get_user
      responses:
        '200':
          description: Current users email
          content:
            application/json:
              schema:
                type: object
                description: LoggedUser
                required:
                - email
                - session
                - secret_key
                - created_at
                properties:
                  created_at:
                    type: string
                    format: date-time
                    description: User Created At
                  email:
                    $ref: '#/components/schemas/str'
                    description: Email Address
                  secret_key:
                    $ref: '#/components/schemas/str'
                    description: Secret Key
                  session:
                    type: string
                    format: uuid
                    description: Session ID
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    $ref: '#/components/schemas/str'
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    $ref: '#/components/schemas/str'
    post:
      operationId: test_login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        '201':
          description: Login POST
          content:
            application/json:
              schema:
                type: object
                description: LoggedUser
                required:
                - email
                - session
                - secret_key
                - created_at
                properties:
                  created_at:
                    type: string
                    format: date-time
                    description: User Created At
                  email:
                    $ref: '#/components/schemas/str'
                    description: Email Address
                  secret_key:
                    $ref: '#/components/schemas/str'
                    description: Secret Key
                  session:
                    type: string
                    format: uuid
                    description: Session ID
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    $ref: '#/components/schemas/str'
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    $ref: '#/components/schemas/str'
components:
  schemas:
    AuthRequest:
      type: object
      required:
      - email
      - password
      properties:
        email:
          $ref: '#/components/schemas/str'
          description: Email Address
        password:
          $ref: '#/components/schemas/str'
          description: Password
    EmailStats:
      type: object
      required:
      - bounces
      - complaints
      - delivery_attempts
      - rejects
      properties:
        bounces:
          type: integer
          format: int64
          description: Number of Bounced Emails
        complaints:
          type: integer
          format: int64
          description: Number of Complaints
        delivery_attempts:
          type: integer
          format: int64
          description: Number of Delivery Attempts
        max_timestamp:
          type:
          - string
          - 'null'
          format: date-time
          description: Latest Record
        min_timestamp:
          type:
          - string
          - 'null'
          format: date-time
          description: Earliest Record
        rejects:
          type: integer
          format: int64
          description: Number of Rejected Emails
    LoggedUser:
      type: object
      description: LoggedUser
      required:
      - email
      - session
      - secret_key
      - created_at
      properties:
        created_at:
          type: string
          format: date-time
          description: User Created At
        email:
          $ref: '#/components/schemas/str'
          description: Email Address
        secret_key:
          $ref: '#/components/schemas/str'
          description: Secret Key
        session:
          type: string
          format: uuid
          description: Session ID
    SesQuotas:
      type: object
      description: SesQuotas
      required:
      - max_24_hour_send
      - max_send_rate
      - sent_last_24_hours
      properties:
        max_24_hour_send:
          type: number
          format: double
          description: Maximum Emails per Day
        max_send_rate:
          type: number
          format: double
          description: Maximum Emails per Second
        sent_last_24_hours:
          type: number
          format: double
          description: Emails Send in Last Day
    SessionSummary:
      type: object
      description: SessionSummary
      required:
      - session_id
      - email_address
      - last_accessed
      - created_at
      - number_of_data_objects
      properties:
        created_at:
          type: string
          format: date-time
          description: Create At
        email_address:
          $ref: '#/components/schemas/str'
          description: Email Address
        last_accessed:
          type: string
          format: date-time
          description: Last Accessed
        number_of_data_objects:
          type: integer
          format: int64
          description: Number of Data Objects
        session_id:
          type: string
          format: uuid
          description: Session ID
    str:
      type: string
