name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize DB
      run: sh ./scripts/bootstrap_db.sh
    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: postgresql://user:password@host:1234/test_db
