name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12.4-alpine
        env:
          POSTGRES_DB: auth_server_rust
          POSTGRES_PASSWORD: 2UtcMAAvNuBHPqK9
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic

    - name: Outdated
      run: |
        cargo install cargo-outdated && \
        cargo outdated -d2

    - name: Unused Deps
      run: |
        rustup update nightly && \
        cargo +nightly install cargo-udeps && \
        cargo +nightly udeps

    - name: Build
      run: |
        cargo build && \
        ./target/debug/auth-server-admin run-migrations
      env:
        DATABASE_URL: postgresql://postgres:2UtcMAAvNuBHPqK9@localhost:5432/auth_server_rust

    - name: Run tests / generate code coverage
      run: |
        mkdir -p ${HOME}/.config/auth_server_rust && \
        cargo test --workspace && \
        cargo install cargo-tarpaulin && \
        cargo tarpaulin --all-features --workspace --out xml
      env:
        DATABASE_URL: postgresql://postgres:2UtcMAAvNuBHPqK9@localhost:5432/auth_server_rust
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
        SENDING_EMAIL_ADDRESS: ${{secrets.SENDING_EMAIL_ADDRESS}}
        GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
        GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
        DOMAIN: localhost

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
