name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic
    - name: Build
      run: cargo build --verbose
    - name: Start Postgres
      run: sh ./scripts/bootstrap_github.sh
      env:
        PASSWORD: 807bXYSp7ynpPeIJ
    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: postgresql://postgres:807bXYSp7ynpPeIJ@localhost:12345/auth_server_rust
